### ISSUE TITLE
Support for Historical Conversation in RESDSQL

### ISSUE THREAD

**Issue by Zeke-chin** [RUCKBReasoning/RESDSQL#58]
I have a few questions regarding the implementation and support for historical conversations in RESD-SQL:

1. Can RESD-SQL support historical conversations?
   I have reviewed the design for the T5 model input structure `"question | table.columns ..."` and would like to inquire about the feasibility of including historical conversation support.

2. Is it possible to add ·'history' to the 'question' section of the input?
   like `"question [SEP] history  | table.columns ..."`
   I am aware that such an implementation may not yield effective results without the support of a pretrained model. However, incorporating historical data into the pretrained model may enable support for at least one round of dialogue. Do you have any suggestions or advice regarding this approach?

4. Do you have any experiments or recommendations regarding support for context in conversational models?

I look forward to any guidance or insights you may have on these matters.

**Comment by lihaoyang-ruc** [comment]
Hi! This is a good question.

1. Can RESD-SQL support historical conversations?
Yes, any seq2seq model can support historical conversations.

2. Is it possible to add ·'history' to the 'question' section of the input?
Yes, a feasible approach to make the language model support conversation is to simply concatenate the conversation history, the current new question, and the database schema sequence using a separator like `question [SEP] history | table.columns`. However, it's important to note that at each dialog round, you should modify the inference procedure to retrieve new relevant schema items and update the database schema sequence accordingly. Additionally, it's worth mentioning that directly using our published checkpoints may not yield satisfactory performance since our models are trained on Spider, which is a single-turn text-to-SQL benchmark. Therefore, I would recommend fine-tuning a new T5 (or other powerful seq2seq models) to adapt to this new input format.

3. Do you have any experiments or recommendations regarding support for context in conversational models?
I'm aware that some benchmarks are explicitly designed for conversational (or multi-round) text-to-SQL, such as CoSQL (https://yale-lily.github.io/cosql) and SParC (https://yale-lily.github.io/sparc). While I haven't personally conducted experiments related to these benchmarks, I believe that the capabilities of current language models should indeed lead to impressive performance on this task, provided that you have adequately prepared the training and testing data.

**Comment by Zeke-chin** [comment]
Thank you for your response 🙏. 

I fully understand your points. 
Looking forward to seeing your team shine on the CoSQL leaderboard 😊.

**Comment by lihaoyang-ruc** [comment]
We currently don't have plans for this, but your suggestion has inspired us, and we might try something with CoSQL in the future. Thank you!🤗

**Comment by Zeke-chin** [comment]
I got it. Thanks all you and your team have done.
