### ISSUE TITLE
How can I finetune on CSpider

### ISSUE THREAD

**Issue by wikty** [RUCKBReasoning/RESDSQL#7]

**Comment by lihaoyang-ruc** [comment]
This is an interesting issue.

Currently, our method is fine-tuned for English RoBERTa and T5, since the datasets used in our paper are in English. In fact, RESDSQL is a general method and is not limited by language. Therefore, we also want to know if RESDSQL can achieve promising performance on multilingual Text-to-SQL benchmarks such as CSpider.

You can replace the original English RoBERTa and T5 with multilingual RoBERTa and T5 that support both Chinese and English, and then fine-tune them.

Although it sounds easy, there are still potential problems that may be encountered during implementation. Good luck!

**Comment by wikty** [comment]
Thank you very much, that sounds very reasonable!

Training on Chinese-English bilingual datasets has great significance. For example, in a real industry scene our user input is in Chinese, but the database schema is in English. I'll try your proposal idea.

I still have a little concern about `preprocessing.py`, does it bind with English?

**Comment by wikty** [comment]
Thanks a lot, I'll try it out.
